import { requireGroup, participantAction, targetJids, mentionText, setGroupToggle, safeTargets } from '../services/group.js';
import { getState } from '../lib/state.js';
const def=(name,aliases,usage,help,execute,extra={})=>({name,version:'15.0.3',aliases,usage,help,groupOnly:true,groupAdminOnly:true,...extra,execute});
export const commands={
 add:def('add',['invite'],'add <nomor>','Tambah member',async({sock,m,args})=>{try{const r=await participantAction(sock,m,args,'add');return m.reply({text:`Add selesai: ${r.map(x=>`${x.jid}=${x.status}`).join(', ')}`});}catch(e){return m.reply({text:e.message});}}),
 kick:def('kick',['remove','del'],'kick <tag/reply/nomor>','Keluarkan member',async({sock,m,args})=>{try{const r=await participantAction(sock,m,args,'remove');return m.reply({text:`Kick selesai: ${r.map(x=>`${x.jid}=${x.status}`).join(', ')}`});}catch(e){return m.reply({text:e.message});}}),
 promote:def('promote',['promot'],'promote <tag/reply>','Jadikan admin',async({sock,m,args})=>{try{await participantAction(sock,m,args,'promote');return m.reply({text:'Promote selesai.'});}catch(e){return m.reply({text:e.message});}}),
 demote:def('demote',['demot'],'demote <tag/reply>','Turunkan admin',async({sock,m,args})=>{try{await participantAction(sock,m,args,'demote');return m.reply({text:'Demote selesai.'});}catch(e){return m.reply({text:e.message});}}),
 setname:def('setname',['groupname','subject'],'setname <nama>','Ubah nama group',async({sock,m,rawArgs})=>{try{requireGroup(m);if(!rawArgs.trim())throw new Error('Nama kosong.');await sock.groupUpdateSubject(m.chat,rawArgs.trim());return m.reply({text:'Nama group diperbarui.'});}catch(e){return m.reply({text:e.message});}}),
 setdesc:def('setdesc',['groupdesc','description'],'setdesc <deskripsi>','Ubah deskripsi group',async({sock,m,rawArgs})=>{try{requireGroup(m);await sock.groupUpdateDescription(m.chat,rawArgs.trim());return m.reply({text:'Deskripsi group diperbarui.'});}catch(e){return m.reply({text:e.message});}}),
 linkgroup:def('linkgroup',['grouplink','link'],'linkgroup','Ambil link group',async({sock,m})=>{try{requireGroup(m);const c=await sock.groupInviteCode(m.chat);return m.reply({text:`https://chat.whatsapp.com/${c}`});}catch(e){return m.reply({text:e.message});}}),
 revoke:def('revoke',['resetlink'],'revoke','Reset link group',async({sock,m})=>{try{requireGroup(m);const c=await sock.groupRevokeInvite(m.chat);return m.reply({text:`Link baru:\nhttps://chat.whatsapp.com/${c}`});}catch(e){return m.reply({text:e.message});}}),
 tagall:def('tagall',['everyone','mentionall'],'tagall [pesan]','Mention semua member',async({m,rawArgs})=>{try{requireGroup(m);const jids=(m.group?.participants||[]).map(p=>p.id||p.phoneNumber||p.lid).filter(Boolean);return m.reply({text:`${rawArgs.trim()||'Attention'}\n\n${mentionText(jids)}`,mentions:jids});}catch(e){return m.reply({text:e.message});}}),
 hidetag:def('hidetag',['silenttag'],'hidetag <pesan>','Mention semua tanpa menampilkan mention',async({m,rawArgs})=>{try{requireGroup(m);const jids=(m.group?.participants||[]).map(p=>p.id||p.phoneNumber||p.lid).filter(Boolean);return m.reply({text:rawArgs.trim()||'🔔',mentions:jids});}catch(e){return m.reply({text:e.message});}}),
 kickall:def('kickall',['removeall'],'kickall','Keluarkan member non-admin',async({sock,m})=>{try{requireGroup(m);const jids=safeTargets(m).map(p=>p.id||p.phoneNumber||p.lid).filter(Boolean);if(!jids.length)return m.reply({text:'Tidak ada target aman untuk kickall.'});const r=await sock.groupParticipantsUpdate(m.chat,jids,'remove');return m.reply({text:`Kickall diproses: ${r.length} member.`});}catch(e){return m.reply({text:e.message});}}),
 welcome:def('welcome',['setwelcome'],'welcome on|off','Aktif/nonaktif welcome',async({m,args})=>{try{requireGroup(m);const v=(args[0]||'status').toLowerCase();if(v==='status')return m.reply({text:`Welcome: ${getState().groupSettings?.[m.chat]?.welcome?'ON':'OFF'}`});await setGroupToggle(m.chat,'welcome',v==='on');return m.reply({text:`Welcome ${v==='on'?'ON':'OFF'}.`});}catch(e){return m.reply({text:e.message});}}),
 leave:def('leave',['setleave'],'leave on|off','Aktif/nonaktif leave notification',async({m,args})=>{try{requireGroup(m);const v=(args[0]||'status').toLowerCase();if(v==='status')return m.reply({text:`Leave: ${getState().groupSettings?.[m.chat]?.leave?'ON':'OFF'}`});await setGroupToggle(m.chat,'leave',v==='on');return m.reply({text:`Leave ${v==='on'?'ON':'OFF'}.`});}catch(e){return m.reply({text:e.message});}}),
 close:def('close',['groupclose'],'close','Hanya admin yang dapat chat',async({sock,m})=>{try{requireGroup(m);await sock.groupSettingUpdate(m.chat,'announcement');return m.reply({text:'Group ditutup untuk member.'});}catch(e){return m.reply({text:e.message});}}),
 open:def('open',['groupopen'],'open','Buka chat group',async({sock,m})=>{try{requireGroup(m);await sock.groupSettingUpdate(m.chat,'not_announcement');return m.reply({text:'Group dibuka.'});}catch(e){return m.reply({text:e.message});}}),
 lock:def('lock',['grouplock'],'lock','Kunci info group untuk admin',async({sock,m})=>{try{requireGroup(m);await sock.groupSettingUpdate(m.chat,'locked');return m.reply({text:'Edit info group dibatasi admin.'});}catch(e){return m.reply({text:e.message});}}),
 unlock:def('unlock',['groupunlock'],'unlock','Buka edit info group',async({sock,m})=>{try{requireGroup(m);await sock.groupSettingUpdate(m.chat,'unlocked');return m.reply({text:'Edit info group dibuka.'});}catch(e){return m.reply({text:e.message});}})
, approve:def('approve',['approvejoin'],'approve <jid>','Setujui request join',async({sock,m,args})=>{try{requireGroup(m);const j=targetJids(m,args);if(!j.length)throw new Error('JID/tag diperlukan.');const r=await sock.groupRequestParticipantsUpdate(m.chat,j,'approve');return m.reply({text:`Approve: ${r.map(x=>`${x.jid}=${x.status}`).join(', ')}`});}catch(e){return m.reply({text:e.message});}})
, reject:def('reject',['rejectjoin'],'reject <jid>','Tolak request join',async({sock,m,args})=>{try{requireGroup(m);const j=targetJids(m,args);if(!j.length)throw new Error('JID/tag diperlukan.');const r=await sock.groupRequestParticipantsUpdate(m.chat,j,'reject');return m.reply({text:`Reject: ${r.map(x=>`${x.jid}=${x.status}`).join(', ')}`});}catch(e){return m.reply({text:e.message});}})
, requests:def('requests',['joinrequests'],'requests','Lihat request join',async({sock,m})=>{try{requireGroup(m);const r=await sock.groupRequestParticipantsList(m.chat);return m.reply({text:r.length?r.map((x,i)=>`${i+1}. ${x.jid||x.id||JSON.stringify(x)}`).join('\n'):'Tidak ada request.'});}catch(e){return m.reply({text:e.message});}})
, ephemeral:def('ephemeral',['disappearing'],'ephemeral <off|24h|7d|90d>','Atur pesan sementara',async({sock,m,args})=>{try{requireGroup(m);const map={off:0,'24h':86400,'7d':604800,'90d':7776000};const v=map[String(args[0]||'').toLowerCase()];if(v===undefined)throw new Error('Pilihan: off, 24h, 7d, 90d');await sock.groupToggleEphemeral(m.chat,v);return m.reply({text:`Ephemeral: ${args[0]}`});}catch(e){return m.reply({text:e.message});}})

};
