import {parseTargetJid,createMenfess,getMenfessById,findSessionFromQuoted,registerMessageId,addMessageToSession,closeMenfess,menfessStatus,sessionForUser} from '../lib/menfess.js';
import {button,sendButtons} from '../services/buttons.js';
export default {name:'menfess',version:'17.0.0',aliases:['mf','confess'],usage:'menfess <nomor> | <pesan>|menfess reply <id> <pesan>|menfess close <id>',category:'social',help:'Secret message / anonymous conversation dengan session, expiry dan quote tracking',async execute({m,args,prefix,sock}){
 const action=String(args[0]||'').toLowerCase();
 if(action==='status'){const s=args[1]?menfessStatus(args[1]):sessionForUser(m.sender)&&menfessStatus(sessionForUser(m.sender).id);return m.reply({text:s?`*MENFESS STATUS v17*\nID: ${s.id}\nStatus: ${s.status}\nAlias: ${s.alias}\nMessages: ${s.historyCount}\nExpired: ${new Date(s.expiresAt).toISOString()}`:'Tidak ada sesi menfess aktif.'});}
 if(action==='close'){const id=args[1];const s=getMenfessById(id);if(!s)return m.reply({text:'Menfess ID tidak ditemukan.'});if(m.sender!==s.sender&&m.sender!==s.recipient)return m.reply({text:'Kamu bukan peserta sesi ini.'});closeMenfess(id);return m.reply({text:`Menfess ${id.toUpperCase()} ditutup.`});}
 if(action==='reply'){const id=args[1],text=args.slice(2).join(' ').trim(),s=getMenfessById(id);if(!s)return m.reply({text:'Menfess ID tidak ditemukan atau expired.'});if(!text)return m.reply({text:`${prefix}menfess reply ${id} <pesan>`});if(m.sender!==s.sender&&m.sender!==s.recipient)return m.reply({text:'Kamu bukan peserta sesi ini.'});const target=m.sender===s.sender?s.recipient:s.sender;addMessageToSession(s,m.sender,text);const out=await sock.sendMessage(target,{text:`*MENFESS ${s.id}*\n${s.alias}\n\n${text}\n\nBalas dengan: ${prefix}menfess reply ${s.id} <pesan>`});if(out?.key?.id)registerMessageId(out.key.id,s.id);return m.reply({text:`Pesan dikirim ke ${target.split('@')[0]}.`});}
 const raw=args.join(' ').trim();const sep=raw.split('|');if(sep.length<2)return m.reply({text:`*MENFESS v17*\n\nBuat:\n${prefix}menfess 628xxxx | pesan\n\nBalas:\n${prefix}menfess reply MF-XXXXXX pesan\n\nStatus:\n${prefix}menfess status`});const target=parseTargetJid(sep[0]);const message=sep.slice(1).join('|').trim();if(!target)return m.reply({text:'Nomor tujuan tidak valid.'});if(target===m.sender)return m.reply({text:'Tujuan harus berbeda dari pengirim.'});const s=createMenfess({sender:m.sender,senderName:m.pushName,recipient:target,message,ttlMs:86400000});const out=await sock.sendMessage(target,{text:`*MENFESS ${s.id}*\n${s.alias}\n\n${message}\n\nBalas dengan: ${prefix}menfess reply ${s.id} <pesan>`});if(out?.key?.id)registerMessageId(out.key.id,s.id);return sendButtons(m,{text:`Menfess ${s.id} terkirim. Sesi aktif 24 jam.`,buttons:[button(`${prefix}menfess status`,'Status'),button(`${prefix}menfess close ${s.id}`,'Close'),button(`${prefix}menu social`,'Menu')]});
}};
