import { updateMenuConfig, getMenuConfig, MENU_CATEGORIES } from '../services/menu.js';
export default { name:'menuset', version:'15.0.3', aliases:['menuctl'], usage:'menuset <setting> <value>', ownerOnly:true, category:'owner', help:'Owner: atur tampilan, filter, font, widget, dan type menu', async execute({m,args}) {
  const key=String(args[0]||'status').toLowerCase(); const cfg=getMenuConfig();
  if(key==='status') return m.reply({text:`*MENU SETTINGS v15.0*\nType: ${cfg.type}\nSort: ${cfg.sort}\nNumbered: ${cfg.numbered}\nDescription: ${cfg.showDescription}\nArgs: ${cfg.showArgs}\nFont: ${cfg.font}\nHidden: ${cfg.hidden.join(', ')||'-'}\nWidgets: ${Object.entries(cfg.widgets).filter(([,v])=>v).map(([k])=>k).join(', ')||'-'}`});
  if(key==='ignore') { const what=String(args[1]||'').toLowerCase(); if(what==='desc'||what==='description') await updateMenuConfig({showDescription:false}); else if(what==='args') await updateMenuConfig({showArgs:false}); else if(what==='none') await updateMenuConfig({showDescription:true,showArgs:true}); else return m.reply({text:'Contoh: .menuset ignore desc | args | none'}); return m.reply({text:`Menu updated: ${what}`}); }
  if(key==='show') { const what=String(args[1]||'').toLowerCase(); if(what==='desc'||what==='description') await updateMenuConfig({showDescription:true}); else if(what==='args') await updateMenuConfig({showArgs:true}); else if(what==='number') await updateMenuConfig({numbered:true}); else if(what==='all') await updateMenuConfig({showDescription:true,showArgs:true,numbered:true}); else return m.reply({text:'Contoh: .menuset show desc|args|number|all'}); return m.reply({text:'Menu updated.'}); }
  if(key==='number') { await updateMenuConfig({numbered:['on','true','yes'].includes(String(args[1]).toLowerCase())}); return m.reply({text:'Numbered menu updated.'}); }
  if(key==='sort') { const v=String(args[1]||'category').toLowerCase(); if(!['category','az'].includes(v)) return m.reply({text:'Sort: category atau az'}); await updateMenuConfig({sort:v}); return m.reply({text:`Sort menu: ${v}`}); }
  if(key==='type') { const v=String(args[1]||'buttons').toLowerCase(); if(!['text','image','buttons','list','carousel'].includes(v)) return m.reply({text:'Type: text|image|buttons|list|carousel'}); await updateMenuConfig({type:v}); return m.reply({text:`Menu type: ${v}`}); }
  if(key==='font') { const v=String(args[1]||'normal').toLowerCase(); if(!['normal','mono','bold'].includes(v)) return m.reply({text:'Font: normal|mono|bold'}); await updateMenuConfig({font:v}); return m.reply({text:`Font menu: ${v}`}); }
  if(key==='replace') { const from=String(args[1]||''); const to=String(args.slice(2).join(' ')||''); if(!from||from.length>4||to.length>4) return m.reply({text:'Gunakan .menuset replace <simbol> <pengganti> (maks 4 karakter).'}); const replaces={...(cfg.replaces||{})}; replaces[from]=to; await updateMenuConfig({replaces}); return m.reply({text:`Replace simbol disimpan: ${from} → ${to}`}); }
  if(key==='widget') { const w=String(args[1]||'').toLowerCase(); const val=['on','true','show','1'].includes(String(args[2]||'on').toLowerCase()); if(!['stats','novel','links','user','premium','status'].includes(w)) return m.reply({text:'Widget: stats|novel|links|user|premium|status'}); await updateMenuConfig({widgets:{[w]:val}}); return m.reply({text:`Widget ${w}: ${val?'ON':'OFF'}`}); }
  if(key==='hide'||key==='showcmd') { const name=String(args[1]||'').replace(/^[-.]/,'').toLowerCase(); if(!name) return m.reply({text:'Contoh: .menuset hide ping'}); const set=new Set(cfg[key==='hide'?'hidden':'shown']); set.add(name); if(key==='hide') await updateMenuConfig({hidden:[...set]}); else await updateMenuConfig({shown:[...set]}); return m.reply({text:`Command ${name} updated.`}); }
  if(key==='category') { const c=String(args[1]||'').toLowerCase(); if(!['all',...MENU_CATEGORIES,'game.combat','game.character','game.world','game.progression','game.dashboard'].includes(c)) return m.reply({text:`Category: ${['all',...MENU_CATEGORIES,'game.combat','game.character','game.world','game.progression','game.dashboard'].join(' | ')}`}); await updateMenuConfig({category:c}); return m.reply({text:`Default menu category: ${c}`}); }
  if(key==='reset') { await updateMenuConfig({showDescription:true,showArgs:true,numbered:false,sort:'category',type:'buttons',font:'normal',widgets:{stats:true,novel:false,links:false,user:true,premium:true,status:true},hidden:[],shown:[]}); return m.reply({text:'Menu settings reset.'}); }
  return m.reply({text:'MenuSet: status | ignore | show | number | sort | type | font | replace | widget | hide | showcmd | category | reset'});
} };
