import sharp from 'sharp';
import { cacheGetOrSet } from './smart-cache.js';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const W=1200,H=675;
function frame(title,sub='NEXORA RPG v16'){return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#070b16"/><stop offset="1" stop-color="#121a2d"/></linearGradient><linearGradient id="bar"><stop offset="0" stop-color="#57e6ff"/><stop offset="1" stop-color="#8d7aff"/></linearGradient></defs><rect width="1200" height="675" rx="28" fill="url(#bg)"/><rect x="32" y="32" width="1136" height="611" rx="24" fill="none" stroke="#263452"/><text x="70" y="82" fill="#f5f7ff" font-family="Arial" font-size="30" font-weight="700">${esc(title)}</text><text x="70" y="110" fill="#72809e" font-family="Arial" font-size="14">${esc(sub)}</text>`}
const close=()=>`<text x="70" y="625" fill="#53627f" font-family="Arial" font-size="13">NEXORA RPG ENGINE • event-sourced combat • smart cache • persistent memory</text></svg>`;
async function png(key,svg,ttl=300000){const b64=await cacheGetOrSet(`canvas:v16:${key}`,async()=> (await sharp(Buffer.from(svg)).png().toBuffer()).toString('base64'),ttl);return Buffer.from(b64,'base64');}
function bar(x,y,w,h,pct){const p=Math.max(0,Math.min(1,Number(pct)||0));return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${h/2}" fill="#1b2438"/><rect x="${x}" y="${y}" width="${w*p}" height="${h}" rx="${h/2}" fill="url(#bar)"/>`;}

export async function renderBattleSelectionCanvas(enemies=[], player={}){
 const rows=enemies.slice(0,7).map((e,i)=>`<rect x="60" y="${155+i*60}" width="1080" height="48" rx="12" fill="#10182a" stroke="#263452"/><text x="80" y="${185+i*60}" fill="#57e6ff" font-size="16" font-family="Arial" font-weight="700">${i+1}. ${esc(e.name)}</text><text x="510" y="${185+i*60}" fill="#c8d0e3" font-size="14" font-family="Arial">Lv.${e.level} • HP ${e.hp} • ${esc(e.type)}</text><text x="890" y="${185+i*60}" fill="#ffd166" font-size="13" font-family="Arial">${e.xp} XP • ${e.coins} C</text>`).join('');
 const svg=frame('BATTLE GATE','Choose an enemy • native list + visual codex')+`<text x="70" y="135" fill="#fff" font-size="18" font-family="Arial">PLAYER Lv.${player.level||1} • HP ${player.hp||0}/${player.maxHp||0} • MP ${player.mp||0}/${player.maxMp||0}</text>${rows}${close()}`;
 return png(`battle-select:${JSON.stringify(enemies.map(e=>e.id))}:${player.level||1}`,svg,30000);
}
export async function renderSkillBookCanvas(skills=[],snapshot={}){
 const rows=skills.slice(0,9).map((s,i)=>`<rect x="60" y="${150+i*52}" width="1080" height="40" rx="10" fill="#10182a"/><text x="78" y="${176+i*52}" fill="#57e6ff" font-size="14" font-family="Arial" font-weight="700">${i+1}. ${esc(s.name)}</text><text x="520" y="${176+i*52}" fill="#fff" font-size="13" font-family="Arial">MP ${s.cost} • CD ${s.cd}</text><text x="790" y="${176+i*52}" fill="#9aa6c2" font-size="12" font-family="Arial">${esc(s.kind)}</text>`).join('');
 return png(`skills:${JSON.stringify(skills)}:${snapshot.turn||0}`,frame('SKILL CODEX',`Turn ${snapshot.turn||0} • ${snapshot.enemy?.name||'Battle'}`)+rows+close(),15000);
}

export async function renderCharacterCanvas(profile,stats){const core=['str','agi','dex','int','vit','luk','wis','cha'];const stat=core.map((k,i)=>`<text x="70" y="${190+i*35}" fill="#8b98b4" font-family="Arial" font-size="15">${k.toUpperCase()}</text><text x="155" y="${190+i*35}" fill="#fff" font-family="Arial" font-size="16" font-weight="700">${stats[k]}</text>`).join('');const off=[['ATK',stats.atk],['MATK',stats.matk],['ASPD',stats.aspd],['CRIT',`${stats.crit.toFixed(1)}%`],['CDMG',`${stats.critDmg.toFixed(0)}%`],['PEN',stats.pen],['M.PEN',stats.magicPen],['HIT',stats.hit],['EVA',stats.eva],['DEF',stats.def],['MDEF',stats.mdef],['RES',stats.res],['BLOCK',`${stats.block.toFixed(1)}%`],['PARRY',`${stats.parry.toFixed(1)}%`],['DPS',stats.dps]].map((r,i)=>`<text x="420" y="${175+i*28}" fill="#8b98b4" font-family="Arial" font-size="14">${r[0]}</text><text x="550" y="${175+i*28}" fill="#fff" font-family="Arial" font-size="15" font-weight="700">${esc(r[1])}</text>`).join('');const svg=frame('CHARACTER','Full canvas character sheet')+`<text x="70" y="145" fill="#57e6ff" font-family="Arial" font-size="24" font-weight="700">${esc(profile.name||'PLAYER')} • Lv.${stats.level}</text><text x="760" y="145" fill="#ffd166" font-family="Arial" font-size="20">HP ${stats.maxHp} • MP ${stats.maxMp}</text>${stat}<text x="420" y="140" fill="#57e6ff" font-family="Arial" font-size="18">COMBAT STATS</text>${off}<text x="760" y="220" fill="#8b98b4" font-family="Arial" font-size="15">STAMINA</text>${bar(760,235,350,22,stats.stamina/300)}<text x="760" y="280" fill="#fff" font-family="Arial" font-size="16">${stats.stamina}/300</text><text x="760" y="335" fill="#8b98b4" font-family="Arial" font-size="15">HP REGEN / MP REGEN</text><text x="760" y="365" fill="#fff" font-size="18" font-family="Arial">${stats.hpRegen} / ${stats.mpRegen}</text><text x="760" y="430" fill="#8b98b4" font-size="15" font-family="Arial">EQUIPMENT</text><text x="760" y="458" fill="#fff" font-size="17" font-family="Arial">${profile.equipped?.length||0}/3 slots</text>${close()}`;return png(`character:${profile.id||profile.name||'user'}:${JSON.stringify(stats)}`,svg,60000);}
export async function renderEnemyCanvas(enemy,state={}){const hp=Number(state.hp??enemy.hp),pct=hp/enemy.maxHp;const rows=[['LEVEL',enemy.level],['HP',`${hp}/${enemy.maxHp}`],['MP',`${enemy.mp}/${enemy.maxMp}`],['ATK',enemy.atk],['MATK',enemy.matk],['DEF',enemy.def],['MDEF',enemy.mdef],['ASPD',enemy.aspd],['CRIT',`${enemy.crit.toFixed(1)}%`],['HIT/EVA',`${enemy.hit}/${enemy.eva}`],['DPS',enemy.dps],['XP',enemy.xp],['DROP',enemy.drop]].map((r,i)=>`<text x="70" y="${175+i*30}" fill="#8b98b4" font-family="Arial" font-size="14">${r[0]}</text><text x="260" y="${175+i*30}" fill="#fff" font-family="Arial" font-size="15" font-weight="700">${esc(r[1])}</text>`).join('');const skills=(enemy.skills||[]).map((s,i)=>`<text x="550" y="${180+i*55}" fill="#ff8f8f" font-family="Arial" font-size="18" font-weight="700">${esc(s.name)}</text><text x="550" y="${204+i*55}" fill="#9aa6c2" font-family="Arial" font-size="13">Power ×${s.power} • ${esc(s.element)}${s.status?' • '+esc(s.status):''}</text>`).join('');const svg=frame('ENEMY SCAN',`${enemy.name} • ${enemy.type.toUpperCase()} • Lv.${enemy.level}`)+rows+`<text x="550" y="145" fill="#57e6ff" font-size="18" font-family="Arial">ABILITIES</text>${skills}<text x="550" y="360" fill="#8b98b4" font-size="14" font-family="Arial">HP</text>${bar(550,380,540,28,pct)}<text x="820" y="400" text-anchor="middle" fill="#fff" font-size="14" font-family="Arial">${Math.round(pct*100)}%</text><text x="550" y="470" fill="#ff8f8f" font-size="18" font-family="Arial">THREAT PROFILE</text><text x="550" y="500" fill="#c8d0e3" font-size="14" font-family="Arial">Boss mechanics, CC, damage type, loot and phase data</text>${close()}`;return png(`enemy:${enemy.id}:${hp}`,svg,300000);}
export async function renderBattleProofCanvas(s,result='ongoing'){const p=s.character,e=s.enemy,es=s.enemyState||{};const hp=p.hp/p.maxHp,eh=es.hp/e.maxHp;const buff=(s.buffs||[]).map(x=>`${x.name} ${x.turns}T`).join(' • ')||'—',debuff=(s.debuffs||[]).map(x=>`${x.name} ${x.turns}T`).join(' • ')||'—';const svg=frame('BATTLE PROOF',`${String(result).toUpperCase()} • ${p.level} vs ${e.level} • Turn ${s.turn||0}`)+`<text x="70" y="155" fill="#57e6ff" font-size="20" font-family="Arial" font-weight="700">PLAYER</text><text x="70" y="185" fill="#fff" font-size="18" font-family="Arial">Lv.${p.level} • HP ${p.hp}/${p.maxHp} • MP ${p.mp}/${p.maxMp}</text>${bar(70,205,480,28,hp)}<text x="650" y="155" fill="#ff8f8f" font-size="20" font-family="Arial" font-weight="700">${esc(e.name)}</text><text x="650" y="185" fill="#fff" font-size="18" font-family="Arial">Lv.${e.level} • HP ${es.hp}/${e.maxHp} • MP ${es.mp}/${e.maxMp}</text>${bar(650,205,480,28,eh)}<text x="70" y="285" fill="#8b98b4" font-family="Arial" font-size="14">DAMAGE DEALT</text><text x="70" y="315" fill="#fff" font-size="24" font-family="Arial" font-weight="700">${p.totalDamage}</text><text x="300" y="285" fill="#8b98b4" font-family="Arial" font-size="14">DAMAGE TAKEN</text><text x="300" y="315" fill="#fff" font-size="24" font-family="Arial" font-weight="700">${p.totalTaken}</text><text x="530" y="285" fill="#8b98b4" font-family="Arial" font-size="14">CRITICALS</text><text x="530" y="315" fill="#fff" font-size="24" font-family="Arial" font-weight="700">${p.criticals}</text><text x="760" y="285" fill="#8b98b4" font-family="Arial" font-size="14">RESULT</text><text x="760" y="315" fill="#57e6ff" font-size="24" font-family="Arial" font-weight="700">${esc(result)}</text><text x="70" y="370" fill="#57e6ff" font-size="17" font-family="Arial">ACTIVE BUFFS</text><text x="70" y="398" fill="#c8d0e3" font-size="14" font-family="Arial">${esc(buff)}</text><text x="70" y="445" fill="#ff8f8f" font-size="17" font-family="Arial">ACTIVE DEBUFFS</text><text x="70" y="473" fill="#c8d0e3" font-size="14" font-family="Arial">${esc(debuff)}</text><text x="70" y="525" fill="#8b98b4" font-size="14" font-family="Arial">LAST COMBAT EVENT</text><text x="70" y="553" fill="#fff" font-size="15" font-family="Arial">${esc(s.lastEvent||'—')}</text>${close()}`;return png(`battle:${s.id}:${s.turn}:${p.hp}:${es.hp}:${result}:${buff}:${debuff}`,svg,5000);}
export async function renderDungeonCanvas(dungeon,room=0,enemy=null){const nodes=(dungeon.rooms||[]).map((r,i)=>{const x=110+i*300;return `<circle cx="${x}" cy="300" r="45" fill="#10182a" stroke="${i<room?'#57e6ff':i===room?'#8d7aff':'#293651'}" stroke-width="5"/><text x="${x}" y="307" text-anchor="middle" fill="#fff" font-size="18" font-family="Arial">${i+1}</text><text x="${x}" y="380" text-anchor="middle" fill="#9aa6c2" font-size="13" font-family="Arial">${i<room?'CLEARED':i===room?'CURRENT':'LOCKED'}</text>${i<dungeon.rooms.length-1?`<path d="M${x+48} 300 H${x+252}" stroke="#34405c" stroke-width="6"/>`:''}`}).join('');const svg=frame('DUNGEON',`${dungeon.name} • Req Lv.${dungeon.recommended}`)+`<text x="70" y="155" fill="#c8d0e3" font-size="15" font-family="Arial">${esc(dungeon.story||'')}</text>${nodes}<text x="70" y="470" fill="#57e6ff" font-size="18" font-family="Arial">ROOM ${Math.min(room+1,dungeon.rooms.length)}/${dungeon.rooms.length}</text><text x="70" y="505" fill="#fff" font-size="16" font-family="Arial">${enemy?`Encounter: ${esc(enemy.name)} • ${esc(enemy.type)}`:'Explore the dungeon.'}</text>${close()}`;return png(`dungeon:${dungeon.id}:${room}:${enemy?.id||''}`,svg,60000);}
export async function renderMapCanvas(game={}){const names=['NEXORA HUB','CYBER FOREST','NEON RUINS','QUANTUM ARENA','SINGULARITY CORE'];const nodes=names.map((n,i)=>{const x=110+i*245;return `<circle cx="${x}" cy="320" r="38" fill="#10182a" stroke="${i+1===game.node?'#57e6ff':'#293651'}" stroke-width="5"/><text x="${x}" y="327" text-anchor="middle" fill="#fff" font-size="16" font-family="Arial">${i+1}</text><text x="${x}" y="390" text-anchor="middle" fill="#c8d0e3" font-size="12" font-family="Arial">${esc(n)}</text>${i<4?`<path d="M${x+42} 320 H${x+203}" stroke="#34405c" stroke-width="5"/>`:''}`}).join('');const svg=frame('WORLD MAP','Full canvas world map')+nodes+`<text x="70" y="475" fill="#57e6ff" font-size="18" font-family="Arial">HP ${game.hp||100} • ENERGY ${game.energy||100} • NODE ${game.node||1}/5</text><text x="70" y="510" fill="#9aa6c2" font-size="14" font-family="Arial">Explore → dungeon → encounter → loot → upgrade → story</text>${close()}`;return png(`map:${JSON.stringify(game)}`,svg,60000);}
export async function renderLevelUpCanvas(profile,oldLevel,reward){const svg=frame('LEVEL UP','Progression milestone')+`<text x="70" y="200" fill="#fff" font-size="34" font-family="Arial" font-weight="700">${esc(profile.name||'PLAYER')}</text><text x="70" y="250" fill="#57e6ff" font-size="26" font-family="Arial">Lv.${oldLevel} → Lv.${profile.level}</text><text x="70" y="330" fill="#ffd166" font-size="22" font-family="Arial">${esc(reward?.name||'NEXORA Reward')}</text><text x="70" y="365" fill="#9aa6c2" font-size="15" font-family="Arial">${esc(reward?.rarity||'common')} • ${esc(reward?.effect||'')}</text>${close()}`;return png(`levelup:${profile.id||profile.name}:${oldLevel}:${profile.level}:${reward?.name}`,svg,60000);}
export async function renderInventoryCanvas(profile,items=[]){const rows=items.slice(0,7).map((x,i)=>`<rect x="60" y="${165+i*55}" width="1080" height="45" rx="12" fill="#10182a" stroke="#263452"/><text x="80" y="${194+i*55}" fill="#fff" font-family="Arial" font-size="15">${i+1}. ${esc(x.name)}</text><text x="500" y="${194+i*55}" fill="#57e6ff" font-family="Arial" font-size="14">${esc(x.rarity)} • ${esc(x.type)}</text><text x="780" y="${194+i*55}" fill="#9aa6c2" font-family="Arial" font-size="13">${x.expiresAt?'exp '+new Date(x.expiresAt).toLocaleString('id-ID'):'permanent'}</text>`).join('');const svg=frame('INVENTORY',`${profile.name||'PLAYER'} • ${items.length} items`)+rows+`<text x="70" y="585" fill="#57e6ff" font-size="16" font-family="Arial">Equipment ${profile.equipped?.length||0}/3 • Gacha Keys ${profile.gachaKeys||0}</text>${close()}`;return png(`inventory:${profile.id||profile.name}:${JSON.stringify(items)}`,svg,30000);}
export async function renderLeaderboardCanvas(rows=[]){const body=rows.slice(0,10).map((x,i)=>`<text x="80" y="${175+i*38}" fill="#fff" font-size="16" font-family="Arial">#${i+1} ${esc(x.name||'PLAYER')}</text><text x="580" y="${175+i*38}" fill="#57e6ff" font-size="15" font-family="Arial">Lv.${x.level} • ${x.xp} XP</text><text x="900" y="${175+i*38}" fill="#ffd166" font-size="15" font-family="Arial">${x.coins} coins</text>`).join('');return png(`leaderboard:${JSON.stringify(rows)}`,frame('LEADERBOARD','Global ranking')+body+close(),30000);}
export async function renderProfileCanvas(profile){const svg=frame('PROFILE',`${profile.name||'PLAYER'} • RPG identity`)+`<text x="70" y="190" fill="#fff" font-size="32" font-family="Arial" font-weight="700">${esc(profile.name||'PLAYER')}</text><text x="70" y="240" fill="#57e6ff" font-size="20" font-family="Arial">Lv.${profile.level||1} • ${esc(profile.rank||'Rookie')}</text><text x="70" y="300" fill="#9aa6c2" font-size="17" font-family="Arial">XP ${profile.xp||0} • Coins ${profile.coins||0}</text><text x="70" y="350" fill="#9aa6c2" font-size="17" font-family="Arial">Equipment ${profile.equipped?.length||0}/3 • Keys ${profile.gachaKeys||0}</text>${close()}`;return png(`profile:${profile.id||profile.name}:${profile.level}:${profile.xp}:${profile.coins}`,svg,30000);}
export async function renderMenuCanvas(data={}){const p=Math.max(0,Math.min(1,Number(data.xpProgress||0)/100));const cats=['CORE','GROUP','RPG','DOWNLOAD','AI','ECONOMY','SYSTEM','OWNER','PREMIUM','SOCIAL'];const cat=esc(String(data.category||'all').toUpperCase());const chips=cats.map((x,i)=>`<rect x="${70+(i%5)*215}" y="${315+Math.floor(i/5)*58}" width="190" height="38" rx="12" fill="${x===cat?'#1b3650':'#10182a'}" stroke="${x===cat?'#57e6ff':'#263452'}"/><text x="${165+(i%5)*215}" y="${340+Math.floor(i/5)*58}" text-anchor="middle" fill="#e2e8f0" font-size="12" font-family="Arial" font-weight="700">${x}</text>`).join('');return png(`menu:${JSON.stringify(data)}`,frame('NEXORA COMMAND CENTER','Visual Command System • RPG • AI • Automation')+`<text x="70" y="165" fill="#fff" font-size="28" font-family="Arial" font-weight="700">${esc(data.rank||'Rookie')} • Lv.${data.level||1}</text><text x="70" y="205" fill="#57e6ff" font-size="17" font-family="Arial">XP ${data.xp||0} • Coins ${data.coins||0} • Commands ${data.commands||0}</text><rect x="70" y="230" width="1060" height="14" rx="7" fill="#1b2438"/><rect x="70" y="230" width="${1060*p}" height="14" rx="7" fill="url(#bar)"/><text x="70" y="280" fill="#9aa6c2" font-size="14" font-family="Arial">ACTIVE CATEGORY</text><text x="240" y="280" fill="#fff" font-size="15" font-family="Arial" font-weight="700">${cat}</text>${chips}<text x="70" y="510" fill="#57e6ff" font-size="16" font-family="Arial">Native Flow Ready • Canvas UI • One-tap navigation</text>${close()}`,15000);}
export async function renderCombatHUD(snapshot){return renderBattleProofCanvas(snapshot,'OTW');}
export async function renderStoryCanvas(chapter,scene){const svg=frame(`NEXORA CHRONICLE • CHAPTER ${chapter}`,scene?.title||'')+`<text x="70" y="190" fill="#fff" font-size="26" font-family="Arial">${esc(scene?.title||'Unknown Scene')}</text><text x="70" y="250" fill="#c8d0e3" font-size="17" font-family="Arial">${esc(scene?.text||'')}</text><text x="70" y="340" fill="#57e6ff" font-size="18" font-family="Arial">WORLD STATE</text><text x="70" y="375" fill="#9aa6c2" font-size="15" font-family="Arial">${esc(scene?.state||'The Echo is awakening.')}</text>${close()}`;return png(`story:${chapter}:${scene?.id||scene?.title}`,svg,3600000);}
export async function renderRpgPanelCanvas(title,sub,rows=[]){const body=rows.slice(0,12).map((r,i)=>`<rect x="60" y="${155+i*38}" width="1080" height="30" rx="8" fill="#10182a"/><text x="80" y="${176+i*38}" fill="#c8d0e3" font-family="Arial" font-size="13">${esc(r[0])}</text><text x="540" y="${176+i*38}" fill="#fff" font-family="Arial" font-size="13">${esc(r[1])}</text>`).join('');return png(`panel:${title}:${sub}:${JSON.stringify(rows)}`,frame(title,sub)+body+close(),30000);}

export async function renderMarioCanvas(s){
 const W2=1200,H2=675; const sky=s.theme==='cave'?'#111827':s.theme==='castle'?'#24111b':'#86d7ff'; const ground=s.theme==='cave'?'#374151':s.theme==='castle'?'#4b1d2b':'#4d8c32';
 const px=80+(Math.max(0,Math.min(100,s.progress))/100)*1000; const cells=Array.from({length:18},(_,i)=>{const x=60+i*62;const kind=(i===Math.round((s.progress/100)*17))?'player':(i%7===3?'coin':i%11===5?'enemy':'');return `<rect x="${x}" y="510" width="58" height="45" rx="6" fill="${ground}"/><text x="${x+29}" y="${kind==='coin'?500:kind==='enemy'?500:540}" text-anchor="middle" font-size="25">${kind==='coin'?'🪙':kind==='enemy'?'👾':''}</text>`}).join('');
 const player=`<g><circle cx="${px}" cy="430" r="24" fill="#f5c2a0"/><rect x="${px-27}" y="455" width="54" height="45" rx="12" fill="#e63946"/><rect x="${px-28}" y="495" width="24" height="12" rx="6" fill="#172033"/><rect x="${px+4}" y="495" width="24" height="12" rx="6" fill="#172033"/><rect x="${px-30}" y="420" width="60" height="13" rx="7" fill="#b91c1c"/></g>`;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W2}" height="${H2}"><rect width="1200" height="675" fill="${sky}"/><rect y="510" width="1200" height="165" fill="${ground}"/><text x="55" y="65" fill="#fff" font-family="Arial" font-size="30" font-weight="800">NEXORA RUNNER • ${s.worldName}</text><text x="55" y="95" fill="#fff" font-family="Arial" font-size="16">World ${s.world}/${LEVELS.length} • Turn ${s.turn} • ${s.progress}%</text><text x="820" y="65" fill="#fff" font-family="Arial" font-size="17">❤️ ${s.lives}   🪙 ${s.coins}   ⭐ ${s.score}</text><rect x="55" y="120" width="1090" height="16" rx="8" fill="#25324a"/><rect x="55" y="120" width="${1090*s.progress/100}" height="16" rx="8" fill="#ffd166"/>${cells}${player}<text x="55" y="605" fill="#fff" font-family="Arial" font-size="18">Action: ${s.obstacle} • Power: ${s.power} • Stamina: ${s.stamina}</text><text x="55" y="640" fill="#e5e7eb" font-family="Arial" font-size="13">Orisinal NEXORA platform runner • tombol native untuk bergerak</text></svg>`;
 return png(`mario:${s.world}:${s.x}:${s.y}:${s.lives}:${s.score}:${s.coins}:${s.turn}`,svg,5000);
}
