import { getState, persistMenuConfig } from '../lib/state.js';
const DEFAULTS={showDescription:true,showArgs:true,numbered:false,sort:'category',type:'buttons',font:'normal',widgets:{stats:true,novel:false,links:false,user:true,premium:true,status:true},hidden:[],shown:[],replaces:{}};
export const MENU_CATEGORIES=['core','group','game','download','ai','economy','system','owner','premium','social'];
export const GAME_SUBCATEGORIES={arcade:new Set(['mario','runner','platformer']),combat:new Set(['battle','skill','attack','flee','battleproof','duel','tournament']),character:new Set(['profile','character','inventory','equip','unequip','use','gacha']),world:new Set(['map','enemy','dungeon']),progression:new Set(['quest','achievements','guild','story']),dashboard:new Set(['leaderboard','dashboard'])};
export const MENU_DEFAULTS=structuredClone(DEFAULTS);
export function getMenuConfig(){const raw=getState().menu||{};return {...DEFAULTS,...raw,widgets:{...DEFAULTS.widgets,...(raw.widgets||{})},hidden:[...(raw.hidden||[])],shown:[...(raw.shown||[])],replaces:{...(raw.replaces||{})}};}
function fontApply(text,font='normal'){const maps={normal:null,mono:{'A':'𝙰','B':'𝙱','C':'𝙲','D':'𝙳','E':'𝙴','F':'𝙵','G':'𝙶','H':'𝙷','I':'𝙸','J':'𝙹','K':'𝙺','L':'𝙻','M':'𝙼','N':'𝙽','O':'𝙾','P':'𝙿','Q':'𝚀','R':'𝚁','S':'𝚂','T':'𝚃','U':'𝚄','V':'𝚅','W':'𝚆','X':'𝚇','Y':'𝚈','Z':'𝚉','a':'𝚊','b':'𝚋','c':'𝚌','d':'𝚍','e':'𝚎','f':'𝚏','g':'𝚐','h':'𝚑','i':'𝚒','j':'𝚓','k':'𝚔','l':'𝚕','m':'𝚖','n':'𝚗','o':'𝚘','p':'𝚙','q':'𝚚','r':'𝚛','s':'𝚜','t':'𝚝','u':'𝚞','v':'𝚟','w':'𝚠','x':'𝚡','y':'𝚢','z':'𝚣'},bold:{'A':'𝗔','B':'𝗕','C':'𝗖','D':'𝗗','E':'𝗘','F':'𝗙','G':'𝗚','H':'𝗛','I':'𝗜','J':'𝗝','K':'𝗞','L':'𝗟','M':'𝗠','N':'𝗡','O':'𝗢','P':'𝗣','Q':'𝗤','R':'𝗥','S':'𝗦','T':'𝗧','U':'𝗨','V':'𝗩','W':'𝗪','X':'𝗫','Y':'𝗬','Z':'𝗭','a':'𝗮','b':'𝗯','c':'𝗰','d':'𝗱','e':'𝗲','f':'𝗳','g':'𝗴','h':'𝗵','i':'𝗶','j':'𝗷','k':'𝗸','l':'𝗹','m':'𝗺','n':'𝗻','o':'𝗼','p':'𝗽','q':'𝗾','r':'𝗿','s':'𝘀','t':'𝘁','u':'𝘂','v':'𝘃','w':'𝘄','x':'𝘅','y':'𝘆','z':'𝘇'}};const map=maps[font];return map?String(text).split('').map(c=>map[c]||c).join(''):String(text);}
export {fontApply};
export function getSubcategory(p){const n=String(p.name||'').toLowerCase();if(!String(p.category||'').startsWith('game'))return '';for(const [sub,names] of Object.entries(GAME_SUBCATEGORIES))if(names.has(n))return sub;return 'other';}
export function filterPlugins(plugins,category='all',cfg){let list=plugins.filter(p=>p.hidden!==true);if(category&&category!=='all'){if(category.startsWith('game.'))list=list.filter(p=>String(p.category).toLowerCase()=== 'game.'+category.split('.')[1]);else if(category==='game') list=list.filter(p=>String(p.category||'core').toLowerCase()==='game'||String(p.category||'').toLowerCase().startsWith('game.')); else list=list.filter(p=>String(p.category||'core').toLowerCase()===category);}const hidden=new Set(cfg.hidden.map(x=>x.toLowerCase()));const shown=new Set(cfg.shown.map(x=>x.toLowerCase()));list=list.filter(p=>!hidden.has(String(p.name).toLowerCase())||shown.has(String(p.name).toLowerCase()));if(cfg.sort==='az')list.sort((a,b)=>String(a.name).localeCompare(String(b.name)));else list.sort((a,b)=>String(a.category||'core').localeCompare(String(b.category||'core'))||String(a.name).localeCompare(String(b.name)));return list;}
export function formatCommand(p,prefix,cfg,n){let out=`${prefix}${p.usage||p.name}`;if(!cfg.showArgs)out=out.replace(/\s+<[^>]+>|\s+\[[^\]]+\]/g,'');if(cfg.numbered)out=`${n}. ${out}`;if(cfg.showDescription&&p.help)out+=` — ${p.help}`;for(const [a,b] of Object.entries(cfg.replaces||{}))out=out.split(a).join(b);return fontApply(out,cfg.font);}
export async function updateMenuConfig(patch){const c=getMenuConfig();const n={...c,...patch,widgets:{...c.widgets,...(patch.widgets||{})},hidden:[...(patch.hidden??c.hidden)],shown:[...(patch.shown??c.shown)],replaces:{...c.replaces,...(patch.replaces||{})}};await persistMenuConfig(n);return n;}
