import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import { config } from '../lib/config.js';
const state=new Map(),binDir=path.resolve('./bin'),npmModules=new Map();
function run(command,args,options={}){return new Promise((resolve,reject)=>{const p=spawn(command,args,{stdio:'ignore',...options});p.on('error',reject);p.on('close',c=>c===0?resolve(true):reject(new Error(`${command} exited ${c}`)))})}
export function commandExists(command){const v=String(command||'');if(path.isAbsolute(v))return fs.access(v,fsSync.constants?.X_OK??1).then(()=>true).catch(()=>false);return new Promise(r=>{const p=spawn(process.platform==='win32'?'where':'which',[v],{stdio:'ignore'});p.on('error',()=>r(false));p.on('close',c=>r(c===0))})}
const exists=async f=>fs.access(f,fsSync.constants?.X_OK??1).then(()=>true).catch(()=>false);
async function installYtDlp(){await fs.mkdir(binDir,{recursive:true});const target=path.join(binDir,process.platform==='win32'?'yt-dlp.exe':'yt-dlp');if(await exists(target))return {binary:target};const py=process.env.PYTHON_BIN||(await commandExists('python3')?'python3':(await commandExists('python')?'python':null));if(!py)throw new Error('yt-dlp belum terpasang dan Python tidak tersedia.');try{await run(py,['-m','pip','install','--user','--upgrade','yt-dlp']);const home=path.join(process.env.HOME||'','.local','bin',process.platform==='win32'?'yt-dlp.exe':'yt-dlp');if(await exists(home)){await fs.copyFile(home,target);await fs.chmod(target,0o755).catch(()=>{});return {binary:target}}}catch{}const dir=path.resolve('./.runtime/yt-dlp');await fs.mkdir(dir,{recursive:true});await run(py,['-m','pip','install','--upgrade','--target',dir,'yt-dlp']);if(await fs.access(path.join(dir,'yt_dlp','__main__.py')).then(()=>true).catch(()=>false))return {binary:py,module:dir,runner:'python-module'};throw new Error('Instalasi yt-dlp gagal.')}
export async function ensureYtDlp({background=true}={}){const configured=config.downloader.binary;if(await commandExists(configured))return {ready:true,binary:configured,installed:false};const prev=state.get('yt-dlp-result');if(prev?.ready)return prev;if(state.has('yt-dlp'))return {ready:false,pending:true,binary:configured};const task=(async()=>{try{const r=await installYtDlp();const out={ready:true,installed:true,...r};state.set('yt-dlp-result',out);return out}catch(e){const out={ready:false,error:e.message};state.set('yt-dlp-result',out);throw e}finally{state.delete('yt-dlp')}})();state.set('yt-dlp',task);if(background){task.catch(()=>{});return {ready:false,pending:true,binary:configured}}return task}
export function runtimeDependencyStatus(){return {ytDlp:{pending:state.has('yt-dlp'),...(state.get('yt-dlp-result')||{})}}}
export function ensureNpmModule(name,{background=true}={}){const k=String(name);if(npmModules.has(k))return {pending:true};const t=run(process.env.NPM_BIN||'npm',['install','--no-save',k],{cwd:process.cwd()}).finally(()=>npmModules.delete(k));npmModules.set(k,t);if(background){t.catch(()=>{});return {pending:true}}return t}
