import { config } from './config.js';
const state=new Map();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const TRANSIENT=new Set([408,409,425,429,500,502,503,504]);
function rec(p){let x=state.get(p.id);if(!x){x={failures:0,success:0,cooldownUntil:0,requests:[],remainingRequests:null,remainingTokens:null,last:null};state.set(p.id,x)}return x}
function eligible(p){const s=rec(p);return p.enabled!==false&&p.apiKey&&p.endpoint&&p.model&&Date.now()>=s.cooldownUntil}
function score(p){const s=rec(p),now=Date.now();s.requests=s.requests.filter(t=>now-t<60000);let score=(101-(p.priority||50))+(p.weight||1)*5-s.failures*12;if(s.remainingRequests!=null&&s.remainingRequests<=1)score-=60;if(s.remainingTokens!=null&&s.remainingTokens<=100)score-=50;if(p.rpm&&s.requests.length>=p.rpm)score-=80;return score}
function pick(exclude){return config.ai.providers.filter(p=>eligible(p)&&!exclude.has(p.id)).sort((a,b)=>score(b)-score(a))[0]||null}
function extract(data){if(data?.output_text)return data.output_text;if(Array.isArray(data?.output)){const out=[];for(const item of data.output){for(const c of item?.content||[]){if(typeof c==='string')out.push(c);else if(c?.text)out.push(c.text);else if(c?.type==='output_text'&&c?.text)out.push(c.text)}}if(out.length)return out.join('\n')}if(data?.choices?.[0]?.message?.content)return typeof data.choices[0].message.content==='string'?data.choices[0].message.content:data.choices[0].message.content.map(x=>x.text||'').join('');return data?.choices?.[0]?.text||null}
function mark(p,ok,meta={}){const s=rec(p);s.last={at:Date.now(),ok,...meta};if(ok){s.success++;s.failures=Math.max(0,s.failures-1);if(meta.remainingRequests!=null)s.remainingRequests=meta.remainingRequests;if(meta.remainingTokens!=null)s.remainingTokens=meta.remainingTokens}else{s.failures++;const ms=meta.retryAfter||([401,403].includes(meta.status)?config.ai.cooldownMs:[402,429,500,502,503,504].includes(meta.status)?Math.min(config.ai.cooldownMs*Math.max(1,s.failures),300000):0);if(ms)s.cooldownUntil=Date.now()+ms}}
export function aiHealth(){return config.ai.providers.map(p=>{const s=rec(p);return {id:p.id,name:p.name,model:p.model,available:eligible(p),cooldownUntil:s.cooldownUntil,failures:s.failures,success:s.success,remainingRequests:s.remainingRequests,remainingTokens:s.remainingTokens,last:s.last}})}
function buildBody(p,input,system){if(p.apiMode==='chat')return {model:p.model,messages:system?[{role:'system',content:system},{role:'user',content:String(input)}]:[{role:'user',content:String(input)}]};return {model:p.model,instructions:system||undefined,input:String(input),store:false};}
export async function askWithFallback(input,{system}={}){const tried=new Set();let last={code:'NO_PROVIDER'};for(let i=0;i<config.ai.providers.length;i++){const p=pick(tried);if(!p)break;tried.add(p.id);const s=rec(p);s.requests.push(Date.now());const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),config.ai.timeoutMs);try{const r=await fetch(p.endpoint,{method:'POST',headers:{authorization:`Bearer ${p.apiKey}`,'content-type':'application/json'},body:JSON.stringify(buildBody(p,input,system)),signal:controller.signal});const rr=Number(r.headers.get('x-ratelimit-remaining-requests')),tt=Number(r.headers.get('x-ratelimit-remaining-tokens'));const retry=Number(r.headers.get('retry-after')||0)*1000;if(r.ok){const data=await r.json();const text=extract(data);if(text){mark(p,true,{status:r.status,remainingRequests:Number.isFinite(rr)?rr:null,remainingTokens:Number.isFinite(tt)?tt:null});return {ok:true,text,provider:p.id,model:p.model}}mark(p,false,{status:r.status});last={code:'EMPTY_RESPONSE',provider:p.id,retryable:false};continue}const detail=(await r.text().catch(()=>'' )).slice(0,300);mark(p,false,{status:r.status,retryAfter:retry});last={code:`HTTP_${r.status}`,provider:p.id,detail,retryable:TRANSIENT.has(r.status)};if(retry&&TRANSIENT.has(r.status))await sleep(Math.min(retry,4000));}catch(e){mark(p,false,{status:0});last={code:e?.name==='AbortError'?'TIMEOUT':'NETWORK_ERROR',provider:p.id,detail:e?.message||String(e),retryable:true}}finally{clearTimeout(timer)}}return {...last,ok:false,health:aiHealth()}}
