import crypto from 'node:crypto';
const sessions=new Map();
const messageIdMap=new Map();
const userLastSession=new Map();
export function parseTargetJid(rawNumber){if(!rawNumber)return null;let clean=String(rawNumber).replace(/[^0-9]/g,'');if(clean.startsWith('08'))clean='628'+clean.slice(2);else if(clean.startsWith('8'))clean='628'+clean.slice(1);if(clean.length<9)return null;return clean+'@s.whatsapp.net';}
export function generateMenfessId(){return `MF-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;}
export function createMenfess({sender,senderName,recipient,alias,message,ttlMs=86400000}={}){if(!sender||!recipient||!message?.trim())throw new Error('Sender, recipient dan message wajib.');const id=generateMenfessId(),now=Date.now();const s={id,sender,senderName:senderName||'Sender',recipient,alias:alias?.trim()||'Anonymous',initialMessage:message.trim(),createdAt:now,expiresAt:now+Math.max(60000,ttlMs),status:'active',history:[{from:'sender',senderJid:sender,text:message.trim(),timestamp:now}],botMessageIds:new Set()};sessions.set(id,s);userLastSession.set(sender,id);userLastSession.set(recipient,id);return s;}
export function registerMessageId(stanzaId,menfessId){if(!stanzaId||!menfessId)return;messageIdMap.set(stanzaId,menfessId);sessions.get(menfessId)?.botMessageIds.add(stanzaId);}
export function getMenfessById(id){return sessions.get(String(id||'').toUpperCase().trim())||null;}
export function findSessionFromQuoted(quoted){if(!quoted)return null;const stanzaId=quoted.key?.id;if(stanzaId&&messageIdMap.has(stanzaId))return getMenfessById(messageIdMap.get(stanzaId));const match=String(quoted.text||quoted.body||'').match(/MF-[A-F0-9]{4,8}/i);return match?getMenfessById(match[0]):null;}
export function addMessageToSession(session,senderJid,text){if(!session||session.status!=='active')throw new Error('Menfess sudah ditutup.');if(Date.now()>session.expiresAt){closeMenfess(session.id);throw new Error('Menfess sudah expired.');}const from=senderJid===session.sender?'sender':senderJid===session.recipient?'recipient':null;if(!from)throw new Error('Kamu bukan bagian dari sesi ini.');session.history.push({from,senderJid,text:String(text).trim(),timestamp:Date.now()});userLastSession.set(session.sender,session.id);userLastSession.set(session.recipient,session.id);return session;}
export function closeMenfess(id){const s=getMenfessById(id);if(!s)return false;s.status='closed';sessions.delete(s.id);for(const [mid,mf] of messageIdMap)if(mf===s.id)messageIdMap.delete(mid);return true;}
export function sessionForUser(jid){const id=userLastSession.get(jid);return id?getMenfessById(id):null;}
export function activeSessions(){return [...sessions.values()].filter(s=>s.status==='active'&&Date.now()<s.expiresAt);}
export function menfessStatus(id){const s=getMenfessById(id);if(!s)return null;if(Date.now()>=s.expiresAt){closeMenfess(id);return null;}return {id:s.id,status:s.status,sender:s.sender,recipient:s.recipient,alias:s.alias,createdAt:s.createdAt,expiresAt:s.expiresAt,historyCount:s.history.length};}
