import crypto from 'node:crypto';
import { persistGamification } from './state.js';
import { getUserProfile, getActiveBuffs, addActivity } from './gamification.js';
import { remember } from '../services/memory.js';

export const STAT_KEYS=['str','agi','dex','int','vit','luk','wis','cha'];
export const ENEMY_TYPES=Object.freeze({beast:'Beast',undead:'Undead',machine:'Machine',elemental:'Elemental',boss:'Boss'});
export const STATUS_EFFECTS=Object.freeze({poison:{dot:.05},burn:{dot:.07},bleed:{dot:.06},regen:{hot:.05},freeze:{skip:true},stun:{skip:true},silence:{silence:true},sleep:{skip:true},slow:{speed:.35},armor_break:{defDown:.30},fear:{atkDown:.25},blind:{hitDown:.35},paralyze:{skipChance:.5},curse:{healDown:.5},petrify:{skip:true},confuse:{missChance:.35}});
const enemy=(id,name,type,level,hp,mp,atk,matk,def,mdef,agi,dex,luk,xp,coins,drop,skills,extra={})=>({id,name,type,level,hp,mp,atk,matk,def,mdef,agi,dex,luk,xp,coins,drop,skills,...extra});
export const ENEMIES=Object.freeze({
 slime_scout:enemy('slime_scout','Aqua Slime','beast',1,120,20,14,8,7,5,7,5,4,35,20,'slime-core',[{name:'Splash',power:1.15,element:'water',status:null}]),
 cyber_wolf:enemy('cyber_wolf','Cyber Wolf','beast',3,240,40,27,12,13,8,18,14,8,75,45,'wolf-fang',[{name:'Razor Bite',power:1.35,element:'physical',status:'bleed'}]),
 ruin_guardian:enemy('ruin_guardian','Ruin Guardian','machine',7,620,90,54,25,32,24,9,12,6,180,110,'ancient-core',[{name:'Laser Break',power:1.45,element:'magic',status:'armor_break'}]),
 frost_wraith:enemy('frost_wraith','Frost Wraith','undead',10,880,180,62,72,27,48,22,20,14,320,180,'frost-shard',[{name:'Frozen Veil',power:1.5,element:'ice',status:'freeze'}]),
 ember_reaver:enemy('ember_reaver','Ember Reaver','elemental',13,1250,240,96,105,42,55,27,23,16,520,320,'ember-heart',[{name:'Inferno',power:1.65,element:'fire',status:'burn'},{name:'Rupture',power:1.2,element:'physical',status:'bleed'}]),
 void_harbinger:enemy('void_harbinger','Void Harbinger','undead',17,2200,420,125,145,68,76,31,26,20,900,700,'void-fragment',[{name:'Silence Field',power:1.4,element:'dark',status:'silence'},{name:'Fear Pulse',power:1.3,element:'dark',status:'fear'}]),
 abyss_dragon:enemy('abyss_dragon','Abyss Dragon','boss',20,4800,700,165,150,95,90,34,28,22,1800,1500,'abyss-scale',[{name:'Abyss Roar',power:1.75,element:'dark',status:'fear'},{name:'Inferno Wing',power:1.55,element:'fire',status:'burn'}],{phases:[{at:1,atk:1},{at:.65,atk:1.15},{at:.3,atk:1.35}]})
});
export const DUNGEONS=Object.freeze({
 cyber_forest:{id:'cyber_forest',name:'Cyber Forest Dungeon',recommended:2,story:'Hutan data yang mulai terinfeksi sinyal asing.',rooms:[['slime_scout'],['cyber_wolf'],['cyber_wolf','slime_scout']]},
 neon_ruins:{id:'neon_ruins',name:'Neon Ruins Dungeon',recommended:7,story:'Reruntuhan kota lama menyimpan inti kesadaran pertama.',rooms:[['ruin_guardian'],['frost_wraith'],['ruin_guardian','frost_wraith']]},
 ember_depths:{id:'ember_depths',name:'Ember Depths',recommended:12,story:'Kawah energi tempat fragmen memori terbakar.',rooms:[['ember_reaver'],['ember_reaver','ruin_guardian'],['void_harbinger']]},
 singularity_core:{id:'singularity_core',name:'Singularity Core Raid',recommended:15,story:'Pusat jaringan tempat NEXORA menemukan Echo dirinya.',rooms:[['ruin_guardian'],['frost_wraith','void_harbinger'],['abyss_dragon']]}
});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const uid=m=>String(m?.identity?.pn||m?.identity?.lid||m?.sender||'').toLowerCase();
const freshStatus=()=>({buffs:[],debuffs:[],shields:0});

export function ensureCharacter(m){const u=getUserProfile(m);const g=u.game||={};g.stats||={str:10,agi:10,dex:10,int:10,vit:10,luk:10,wis:10,cha:10};for(const k of STAT_KEYS)g.stats[k]=Number(g.stats[k]??10);g.energy=Number(g.energy??100);g.maxEnergy=Number(g.maxEnergy??100);g.battles||={wins:0,losses:0,kills:0,damage:0,damageTaken:0,criticals:0,turns:0};g.position=Number(g.position||1);g.dungeon??=null;g.battle??=null;return u;}
function equipmentBonuses(u){const b={str:0,agi:0,dex:0,int:0,vit:0,luk:0,wis:0,cha:0,atk:0,matk:0,def:0,mdef:0,hp:0,mp:0,crit:0,critDmg:0,pen:0,magicPen:0,hit:0,eva:0,block:0,parry:0,haste:0,life:0};for(const item of u.inventory||[])if((u.equipped||[]).includes(item.uid)){const id=item.id||'';if(id.includes('coin-boost'))b.luk+=2;if(id.includes('xp-boost'))b.wis+=2;if(id.includes('lucky-core'))b.luk+=8;if(id.includes('nexora-overdrive')){b.atk+=12;b.matk+=12;b.haste+=8;}if(id.includes('singularity')){b.atk+=25;b.matk+=25;b.def+=15;b.mdef+=15;b.crit+=5;}}return b;}
export function characterStats(m){const u=ensureCharacter(m),s=u.game.stats,e=equipmentBonuses(u),level=u.level||1;const maxHp=Math.round(100+s.vit*22+level*30+e.hp),maxMp=Math.round(40+s.int*10+s.wis*6+level*12+e.mp);const atk=Math.round(8+s.str*3+s.dex*.8+level*2+e.atk),matk=Math.round(6+s.int*3.2+s.wis*1.4+level*2+e.matk);const def=Math.round(s.vit*2.4+s.str*.7+level*1.5+e.def),mdef=Math.round(s.wis*2.2+s.int*.8+level*1.2+e.mdef);const aspd=Math.round(100+s.agi*3+s.dex*1.5+e.haste),crit=clamp(3+s.luk*.35+s.dex*.15+e.crit,0,60),critDmg=150+s.luk*.6+e.critDmg,pen=Math.round(s.str*.25+s.dex*.2+e.pen),magicPen=Math.round(s.int*.25+s.wis*.2+e.magicPen),hit=Math.round(80+s.dex*1.2+s.luk*.2+e.hit),eva=Math.round(s.agi*.8+s.dex*.3+e.eva),block=clamp(s.vit*.25+e.block,0,50),parry=clamp(s.agi*.2+e.parry,0,35);const hpRegen=Math.max(1,Math.round(s.vit*.12)),mpRegen=Math.max(1,Math.round(s.wis*.15));const active=getActiveBuffs(u);const combatAtkMult=active.some(x=>/100% XP/.test(x.effect))?1.25:active.some(x=>/50% XP/.test(x.effect))?1.15:1;const combatDefMult=active.some(x=>/100% XP/.test(x.effect))?1.12:1;const finalAtk=Math.round(atk*combatAtkMult),finalMatk=Math.round(matk*combatAtkMult),finalDef=Math.round(def*combatDefMult),finalMdef=Math.round(mdef*combatDefMult);const dps=Math.round(finalAtk*(aspd/100)*(1+(crit/100)*(critDmg/100-1)));return {level,maxHp,maxMp,atk:finalAtk,matk:finalMatk,def:finalDef,mdef:finalMdef,aspd,crit,critDmg,pen,magicPen,hit,eva,block,parry,hpRegen,mpRegen,stamina:clamp(50+s.vit*2,0,300),res:Math.round(s.wis*.5),dps,...s};}
export function enemyStats(id){const e=ENEMIES[id];if(!e)throw new Error('Musuh tidak ditemukan.');return {...e,maxHp:e.hp,maxMp:e.mp,aspd:100+e.agi*3,crit:3+e.luk*.3,critDmg:150,pen:e.dex*.15,magicPen:e.mdef*.08,hit:80+e.dex,eva:e.agi*.7,block:Math.min(40,e.def*.15),parry:Math.min(25,e.agi*.15),res:e.mdef*.25,dps:Math.round(e.atk*(1+e.agi/100)*(1+(e.luk/100)*.25))};}
export function activeCombatBuffs(m){const u=ensureCharacter(m);return [...getActiveBuffs(u),...(u.game.battle?.player?.status?.buffs||[])];}
function stateFor(s){return {hp:s.maxHp,maxHp:s.maxHp,mp:s.maxMp,maxMp:s.maxMp,energy:s.stamina,status:freshStatus(),cooldowns:{},totalDamage:0,totalTaken:0,criticals:0,actions:0};}
export async function startBattle(m,enemyId='cyber_wolf'){const u=ensureCharacter(m);if(u.game.battle?.active)throw new Error('Masih ada pertarungan aktif. Gunakan .skill, .battle status atau .flee.');const e=enemyStats(enemyId),p=characterStats(m);u.game.battle={id:crypto.randomUUID(),active:true,type:'pve',startedAt:new Date().toISOString(),enemyId,turn:0,round:0,player:stateFor(p),enemy:stateFor(e),log:[],lastEvent:'Battle dimulai.',result:'ongoing',proofVersion:1};await remember('combat.start',{battleId:u.game.battle.id,enemyId},uid(m));await persistGamification();return battleSnapshot(m);}
export function battleSnapshot(m){const u=ensureCharacter(m),b=u.game.battle;if(!b)return {active:false,character:characterStats(m),result:'idle'};const p={...characterStats(m),...b.player};const e=enemyStats(b.enemyId);return {active:b.active,id:b.id,type:b.type,turn:b.turn,round:b.round,character:p,enemy:e,enemyState:b.enemy,log:b.log||[],buffs:b.player.status?.buffs||[],debuffs:b.enemy.status?.debuffs||[],lastEvent:b.lastEvent,result:b.result,dungeon:u.game.dungeon};}
function effectiveStats(base,state){let x={...base};for(const b of state.status?.buffs||[]){if(b.atkUp)x.atk=Math.round(x.atk*(1+b.atkUp));if(b.defUp)x.def=Math.round(x.def*(1+b.defUp));if(b.haste)x.aspd=Math.round(x.aspd*(1+b.haste));if(b.invulnerable)x.invulnerable=true;}for(const d of state.status?.debuffs||[]){if(d.defDown)x.def=Math.round(x.def*(1-d.defDown));if(d.atkDown)x.atk=Math.round(x.atk*(1-d.atkDown));if(d.hitDown)x.hit=Math.round(x.hit*(1-d.hitDown));if(d.speed)x.aspd=Math.round(x.aspd*(1-d.speed));}return x;}
function applyStatus(target,status,power=0){if(!status)return;target.status||=freshStatus();if(status==='shield'){target.status.buffs.push({name:'Shield',turns:3,shield:Math.max(40,Math.round(target.maxHp*.18))});return;}const def=STATUS_EFFECTS[status]||{};const arr=target.status.debuffs;const old=arr.find(x=>x.name===status);if(old)old.turns=Math.max(old.turns,2);else arr.push({name:status,turns:2,power:power||.05,...def});}
function tick(state){const logs=[];state.status||=freshStatus();for(const x of [...state.status.debuffs,...state.status.buffs]){if(x.dot){const dmg=Math.max(1,Math.round(state.maxHp*x.dot));state.hp=Math.max(0,state.hp-dmg);logs.push(`${x.name}: -${dmg} HP`);}if(x.hot){const heal=Math.max(1,Math.round(state.maxHp*x.hot));state.hp=Math.min(state.maxHp,state.hp+heal);logs.push(`${x.name}: +${heal} HP`);}if(x.shield)state.status.shields=Math.max(state.status.shields,x.shield);x.turns--;}state.status.debuffs=state.status.debuffs.filter(x=>x.turns>0);state.status.buffs=state.status.buffs.filter(x=>x.turns>0);return logs;}
function damage(attacker,defender,kind='physical'){const magic=kind==='magic';const a=effectiveStats(attacker.stats,attacker.state),d=effectiveStats(defender.stats,defender.state);if(a.invulnerable)return {damage:0,miss:true,reason:'invulnerable'};let hit=clamp(a.hit-(d.eva*.35),35,99);for(const x of attacker.state?.status?.debuffs||[])if(x.name==='blind')hit*=1-x.hitDown;for(const x of attacker.state?.status?.debuffs||[])if(x.name==='confuse'&&Math.random()<x.missChance)return {damage:0,miss:true,reason:'confuse'};if(Math.random()*100>hit)return {damage:0,miss:true};let raw=(magic?a.matk:a.atk)*(.9+Math.random()*.2);let defense=(magic?d.mdef:d.def)-(magic?a.magicPen:a.pen);let out=Math.max(1,Math.round(raw*(100/Math.max(30,100+defense))));const critical=Math.random()*100<a.crit;if(critical)out=Math.round(out*(a.critDmg/100));if(Math.random()*100<d.block)out=Math.round(out*.55);let shield=Math.min(out,Number(defender.state.status?.shields||0));defender.state.status.shields=Math.max(0,(defender.state.status.shields||0)-shield);out-=shield;return {damage:out,critical,shield};}
const SKILLS={basic:{name:'Basic Attack',power:1,kind:'physical',cost:0,cd:0},power:{name:'Power Strike',power:1.65,kind:'physical',cost:18,status:'armor_break',cd:2},arcane:{name:'Arcane Bolt',power:1.55,kind:'magic',cost:22,status:'silence',cd:2},guard:{name:'Aegis Guard',power:0,kind:'buff',cost:15,status:'shield',cd:3},lifeburst:{name:'Life Burst',power:0,kind:'heal',cost:25,status:'regen',cd:3},venom:{name:'Venom Edge',power:1.25,kind:'physical',cost:14,status:'poison',cd:2},inferno:{name:'Inferno Burst',power:1.45,kind:'magic',cost:24,status:'burn',cd:2},frost:{name:'Frost Bind',power:1.15,kind:'magic',cost:22,status:'freeze',cd:3},drain:{name:'Soul Drain',power:1.2,kind:'magic',cost:20,status:'regen',cd:3},lifesteal:{name:'Blood Edge',power:1.3,kind:'physical',cost:20,status:'bleed',cd:3},haste:{name:'Chrono Haste',power:0,kind:'buff',cost:18,status:'haste',cd:4}};
export const SKILL_BOOK=Object.freeze(SKILLS);
function canAct(st){for(const x of st.status?.debuffs||[])if(x.skip&&Math.random()<.9)return false;for(const x of st.status?.debuffs||[])if(x.skipChance&&Math.random()<x.skipChance)return false;return true;}
function useSkill(p,e,name){const s=SKILLS[String(name||'basic').toLowerCase()]||SKILLS.basic;if(p.cooldowns[s.name]>0)throw new Error(`${s.name} cooldown ${p.cooldowns[s.name]} turn.`);if(p.mp<s.cost)throw new Error(`MP tidak cukup (${s.cost}).`);p.mp-=s.cost;p.actions++;if(s.kind==='buff'){applyStatus(p,s.status);p.cooldowns[s.name]=s.cd;if(s.status==='haste')p.status.buffs.push({name:'Haste',turns:3,haste:.25});if(s.status==='regen')p.status.buffs.push({name:'Regen',turns:3,hot:.06});return {skill:s,damage:0,critical:false,heal:s.status==='regen'?0:0};}if(s.kind==='heal'){p.cooldowns[s.name]=s.cd;const heal=Math.max(1,Math.round(p.maxHp*.24));p.hp=Math.min(p.maxHp,p.hp+heal);applyStatus(p,'regen');return {skill:s,damage:0,critical:false,heal};}p.cooldowns[s.name]=s.cd;const r=damage({stats:characterStatsFromState(p),state:p},{stats:enemyStatsFromBattle(e),state:e},s.kind);r.damage=Math.round(r.damage*s.power);e.hp=Math.max(0,e.hp-r.damage);if(s.status)applyStatus(e,s.status);if(r.damage>0&&s.name==='Soul Drain')p.hp=Math.min(p.maxHp,p.hp+Math.round(r.damage*.35));if(r.damage>0&&s.name==='Blood Edge')p.hp=Math.min(p.maxHp,p.hp+Math.round(r.damage*.45));return {...r,skill:s};}
function characterStatsFromState(p){return {atk:p._stats?.atk||p.atk||10,matk:p._stats?.matk||p.matk||10,def:p._stats?.def||p.def||5,mdef:p._stats?.mdef||p.mdef||5,hit:p._stats?.hit||90,eva:p._stats?.eva||5,crit:p._stats?.crit||3,critDmg:p._stats?.critDmg||150,pen:p._stats?.pen||0,magicPen:p._stats?.magicPen||0,block:p._stats?.block||0};}
function enemyStatsFromBattle(e){return {atk:e._stats?.atk||e.atk,matk:e._stats?.matk||e.matk,def:e._stats?.def||e.def,mdef:e._stats?.mdef||e.mdef,hit:e._stats?.hit||e.hit,eva:e._stats?.eva||e.eva,crit:e._stats?.crit||e.crit,critDmg:e._stats?.critDmg||e.critDmg,pen:e._stats?.pen||e.pen,magicPen:e._stats?.magicPen||e.magicPen,block:e._stats?.block||e.block};}
function enemyTurn(b){if(!canAct(b.enemy))return 'Enemy terkena CC dan kehilangan giliran.';const e=enemyStats(b.enemyId),pStats=b.player._stats||characterStatsFromState(b.player);b.enemy._stats=e;const skill=(e.skills||[])[Math.floor(Math.random()*e.skills.length)]||{name:'Attack',power:1,element:'physical'};const kind=skill.element==='physical'?'physical':'magic';const r=damage({stats:e,state:b.enemy},{stats:pStats,state:b.player},kind);r.damage=Math.round(r.damage*skill.power);b.player.hp=Math.max(0,b.player.hp-r.damage);b.enemy.totalDamage=(b.enemy.totalDamage||0)+r.damage;b.player.totalTaken=(b.player.totalTaken||0)+r.damage;if(r.critical)b.enemy.criticals=(b.enemy.criticals||0)+1;if(skill.status)applyStatus(b.player,skill.status);return r.miss?`${e.name}: MISS`:`${e.name} menggunakan ${skill.name}: -${r.damage} HP${r.critical?' CRITICAL':''}${skill.status?` • ${skill.status}`:''}`;}
function resultReward(m,b){const e=enemyStats(b.enemyId),u=ensureCharacter(m);const xp=Math.round(e.xp*(1+(u.level||1)/100));const coins=e.coins;return {xp,coins,drop:e.drop};}
export async function playerTurn(m,name='basic'){const u=ensureCharacter(m),b=u.game.battle;if(!b?.active)throw new Error('Tidak ada battle aktif. Gunakan .battle <enemy>.');const ps=characterStats(m);b.player._stats=ps;b.enemy._stats=enemyStats(b.enemyId);for(const k of Object.keys(b.player.cooldowns||{}))b.player.cooldowns[k]=Math.max(0,b.player.cooldowns[k]-1);b.turn++;b.round++;const logs=tick(b.player);if(canAct(b.player)){let r;try{r=useSkill(b.player,b.enemy,name);}catch(err){b.turn--;throw err;}const skill=r.skill||{name:name};b.lastEvent=r.miss?`${skill.name}: MISS`:`${skill.name}: ${r.heal?`+${r.heal} HP`:`-${r.damage} HP${r.critical?' CRITICAL':''}`}${r.shield?` • Shield ${r.shield}`:''}`;b.log.push(`T${b.turn} PLAYER ${b.lastEvent}`);if(r.damage){b.player.totalDamage+=r.damage;if(r.critical)b.player.criticals++;}}else{b.lastEvent='Player terkena Crowd Control dan kehilangan giliran.';b.log.push(`T${b.turn} ${b.lastEvent}`);}if(b.enemy.hp>0){const enemyLog=enemyTurn(b);b.log.push(`T${b.turn} ENEMY ${enemyLog}`);b.lastEvent+=` | ${enemyLog}`;}logs.push(...tick(b.enemy));if(b.enemy.hp<=0){b.active=false;b.result='victory';b.player.hp=Math.max(1,b.player.hp);u.game.battles.wins++;u.game.battles.kills++;const reward=resultReward(m,b);u.coins=(u.coins||0)+reward.coins;const activity=await addActivity(m,{xp:reward.xp,coins:0});await remember('combat.end',{battleId:b.id,result:'victory',damage:b.player.totalDamage,reward},uid(m));return {...battleSnapshot(m),result:'victory',reward,activity,lastEvent:`${b.lastEvent} • VICTORY`};}if(b.player.hp<=0){b.active=false;b.result='defeat';u.game.battles.losses++;await remember('combat.end',{battleId:b.id,result:'defeat',damage:b.player.totalDamage},uid(m));return {...battleSnapshot(m),result:'defeat',lastEvent:`${b.lastEvent} • DEFEAT`};}await remember('combat.turn',{battleId:b.id,turn:b.turn,event:b.lastEvent,playerHp:b.player.hp,enemyHp:b.enemy.hp},uid(m));await persistGamification();return battleSnapshot(m);}
export async function fleeBattle(m){const u=ensureCharacter(m);if(!u.game.battle?.active)throw new Error('Tidak ada battle aktif.');u.game.battle.active=false;u.game.battle.result='fled';u.game.battle.lastEvent='Player melarikan diri.';await remember('combat.end',{battleId:u.game.battle.id,result:'fled'},uid(m));await persistGamification();return battleSnapshot(m);}
export function listDungeon(){return Object.values(DUNGEONS).map(d=>({id:d.id,name:d.name,recommended:d.recommended,rooms:d.rooms.length,boss:d.rooms.flat().some(x=>ENEMIES[x]?.type==='boss')}));}
export async function startDungeon(m,id){const d=DUNGEONS[id];if(!d)throw new Error('Dungeon tidak ditemukan.');const u=ensureCharacter(m);if((u.level||1)<d.recommended)throw new Error(`Minimal level ${d.recommended}.`);if(u.game.dungeon?.active)throw new Error('Masih berada di dungeon.');u.game.dungeon={id:d.id,active:true,room:0,startedAt:new Date().toISOString(),cleared:[]};await persistGamification();return d;}
export async function enterDungeon(m){const u=ensureCharacter(m),d=u.game.dungeon&&DUNGEONS[u.game.dungeon.id];if(!d)throw new Error('Pilih dungeon dahulu.');if(!u.game.dungeon.active)return {done:true,dungeon:d,room:d.rooms.length};if(u.game.battle?.active)throw new Error('Selesaikan battle dulu.');const room=u.game.dungeon.room,ids=d.rooms[room]||[];const enemyId=ids[0];await startBattle(m,enemyId);u.game.dungeon.room=room+1;if(room+1>=d.rooms.length)u.game.dungeon.active=false;await persistGamification();return {done:false,dungeon:d,room:room+1,battle:battleSnapshot(m)};}
export async function pvpAttack(m,target){throw new Error('PvP direct attack dinonaktifkan di V14; gunakan duel/arena untuk combat terkelola.');}
